//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parameters_Log
    {
        public int LogID { get; set; }
        public string ParamName { get; set; }
        public string ParamDesc { get; set; }
        public string ParamValue { get; set; }
        public string ChangeType { get; set; }
        public System.DateTime ChangeDate { get; set; }
        public int ChangedBy { get; set; }
    
        public virtual User User { get; set; }
    }
}
