//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class RunPayload
    {
        public int PayloadID { get; set; }
        public int RunID { get; set; }
        public string RunPayload1 { get; set; }
    
        public virtual RunWorkflow RunWorkflow { get; set; }
    }
}
