//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwRunWorkflow
    {
        public int RunID { get; set; }
        public int EmpID { get; set; }
        public int WorkflowID { get; set; }
        public Nullable<int> ItemCount { get; set; }
        public string RunStatus { get; set; }
        public System.DateTime StartTime { get; set; }
        public string Username { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string RunDate { get; set; }
    }
}
