//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkflowItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WorkflowItem()
        {
            this.RunItems = new HashSet<RunItem>();
            this.RunResults = new HashSet<RunResult>();
        }
    
        public int WFItemID { get; set; }
        public int WorkflowID { get; set; }
        public int ItemID { get; set; }
        public int RunOrder { get; set; }
        public bool Disabled { get; set; }
    
        public virtual LibraryItem LibraryItem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RunItem> RunItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RunResult> RunResults { get; set; }
        public virtual Workflow Workflow { get; set; }
    }
}
